# Generated by Django 3.0.7 on 2020-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
